In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [ ]:
df=pd.read_csv("/content/Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df['area'].max()

16200

In [ ]:
df['bedrooms'].max()

6

In [ ]:
df['bathrooms'].max()

4

In [ ]:
df['parking'].max()

3

In [ ]:
df['stories'].max()

4

In [ ]:
df['new']=df['bathrooms']+df['bathrooms']+df['stories']+df['parking']

In [ ]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,new
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,9
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,15
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,8
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,9
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,5
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,3
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,3
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,3
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,4

In [ ]:
areaavg=df['area'].mean()
areaavg

5150.54128440367

In [ ]:
newavg=df['new'].mean()
newavg

5.0715596330275226

In [ ]:
ratio=areaavg/newavg

In [ ]:
ratio

1015.5734442836471

In [ ]:
df['House_Area']=df['area']/df['new']
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,new,House_Area
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,9,824.444444
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,15,597.333333
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,8,1245.000000
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,9,833.333333
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,6,1236.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,5,600.000000
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,3,800.000000
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,3,1206.666667
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,3,970.000000
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,4,962.500000

In [ ]:
dataset=df.drop(['bedrooms','stories','parking','new'],axis=1)
dataset

,price,area,bathrooms,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus,House_Area
0,13300000,7420,2,yes,no,no,no,yes,yes,furnished,824.444444
1,12250000,8960,4,yes,no,no,no,yes,no,furnished,597.333333
2,12250000,9960,2,yes,no,yes,no,no,yes,semi-furnished,1245.000000
3,12215000,7500,2,yes,no,yes,no,yes,yes,furnished,833.333333
4,11410000,7420,1,yes,yes,yes,no,yes,no,furnished,1236.666667
...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,1,yes,no,yes,no,no,no,unfurnished,600.000000
541,1767150,2400,1,no,no,no,no,no,no,semi-furnished,800.000000
542,1750000,3620,1,yes,no,no,no,no,no,unfurnished,1206.666667
543,1750000,2910,1,no,no,no,no,no,no,furnished,970.000000
544,1750000,3850,1,yes,no,no,no,no,no,unfurnished,962.500000

In [ ]:
X=dataset.drop('price',axis=1)
X=X.drop('furnishingstatus',axis=1)
scaler = StandardScaler()
X['mainroad'] = X['mainroad'].map({'yes': 1, 'no': 0})
X['guestroom'] = X['guestroom'].map({'yes': 1, 'no': 0})
X['basement'] = X['basement'].map({'yes': 1, 'no': 0})
X['hotwaterheating'] = X['hotwaterheating'].map({'yes': 1, 'no': 0})
X['airconditioning'] = X['airconditioning'].map({'yes': 1, 'no': 0})
X['prefarea'] = X['prefarea'].map({'yes': 1, 'no': 0})
X = scaler.fit_transform(X)
Y= dataset['price'].values
Y=np.log1p(Y)
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

In [ ]:
# Convert data to PyTorch tensors
X_train_tensor = torch.FloatTensor(X_train)
y_train_tensor = torch.FloatTensor(y_train).view(-1, 1)  # Reshape to a column vector
X_test_tensor = torch.FloatTensor(X_test)
y_test_tensor = torch.FloatTensor(y_test).view(-1, 1)  # Reshape to a column vector

# Define the neural network model
class HousePricePredictor(nn.Module):
    def __init__(self, input_size, hidden_size1,hidden_size2, output_size):
        super(HousePricePredictor, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size1)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size1, hidden_size2)
        self.layer3 = nn.Linear(hidden_size2, output_size)

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

# Instantiate the model
input_size = X_train.shape[1]
hidden_size1 = 16  # Adjust as needed
hidden_size2=8
output_size = 1
model = HousePricePredictor(input_size, hidden_size1,hidden_size2, output_size)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
num_epochs = 10000

for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print progress
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Evaluate the model on the test set
with torch.no_grad():
    model.eval()
    predictions = model(X_test_tensor)
    mse = mean_squared_error(y_test, predictions.numpy())
    print(f'Mean Squared Error on Test Set: {mse:.4f}')

Epoch [100/10000], Loss: 168.8221
Epoch [200/10000], Loss: 32.4609
Epoch [300/10000], Loss: 8.6099
Epoch [400/10000], Loss: 4.9083
Epoch [500/10000], Loss: 2.9956
Epoch [600/10000], Loss: 1.9362
Epoch [700/10000], Loss: 1.3744
Epoch [800/10000], Loss: 1.0199
Epoch [900/10000], Loss: 0.7941
Epoch [1000/10000], Loss: 0.6339
Epoch [1100/10000], Loss: 0.5195
Epoch [1200/10000], Loss: 0.4309
Epoch [1300/10000], Loss: 0.3566
Epoch [1400/10000], Loss: 0.2925
Epoch [1500/10000], Loss: 0.2395
Epoch [1600/10000], Loss: 0.2006
Epoch [1700/10000], Loss: 0.1734
Epoch [1800/10000], Loss: 0.1525
Epoch [1900/10000], Loss: 0.1356
Epoch [2000/10000], Loss: 0.1225
Epoch [2100/10000], Loss: 0.1119
Epoch [2200/10000], Loss: 0.1034
Epoch [2300/10000], Loss: 0.0964
Epoch [2400/10000], Loss: 0.0907
Epoch [2500/10000], Loss: 0.0856
Epoch [2600/10000], Loss: 0.0812
Epoch [2700/10000], Loss: 0.0773
Epoch [2800/10000], Loss: 0.0739
Epoch [2900/10000], Loss: 0.0707
Epoch [3000/10000], Loss: 0.0672
Epoch [3100/10000], Loss: 0.0640
Epoch [3200/10000], Loss: 0.0605
Epoch [3300/10000], Loss: 0.0579
Epoch [3400/10000], Loss: 0.0559
Epoch [3500/10000], Loss: 0.0542
Epoch [3600/10000], Loss: 0.0525
Epoch [3700/10000], Loss: 0.0511
Epoch [3800/10000], Loss: 0.0498
Epoch [3900/10000], Loss: 0.0488
Epoch [4000/10000], Loss: 0.0480
Epoch [4100/10000], Loss: 0.0473
Epoch [4200/10000], Loss: 0.0466
Epoch [4300/10000], Loss: 0.0459
Epoch [4400/10000], Loss: 0.0454
Epoch [4500/10000], Loss: 0.0448
Epoch [4600/10000], Loss: 0.0443
Epoch [4700/10000], Loss: 0.0439
Epoch [4800/10000], Loss: 0.0435
Epoch [4900/10000], Loss: 0.0432
Epoch [5000/10000], Loss: 0.0429
Epoch [5100/10000], Loss: 0.0426
Epoch [5200/10000], Loss: 0.0423
Epoch [5300/10000], Loss: 0.0421
Epoch [5400/10000], Loss: 0.0418
Epoch [5500/10000], Loss: 0.0416
Epoch [5600/10000], Loss: 0.0414
Epoch [5700/10000], Loss: 0.0411
Epoch [5800/10000], Loss: 0.0408
Epoch [5900/10000], Loss: 0.0406
Epoch [6000/10000], Loss: 0.0404
Epoch [6100/10000], Loss: 0.0402
Epoch [6200/10000], Loss: 0.0399
Epoch [6300/10000], Loss: 0.0396
Epoch [6400/10000], Loss: 0.0394
Epoch [6500/10000], Loss: 0.0392
Epoch [6600/10000], Loss: 0.0390
Epoch [6700/10000], Loss: 0.0389
Epoch [6800/10000], Loss: 0.0387
Epoch [6900/10000], Loss: 0.0386
Epoch [7000/10000], Loss: 0.0385
Epoch [7100/10000], Loss: 0.0384
Epoch [7200/10000], Loss: 0.0383
Epoch [7300/10000], Loss: 0.0382
Epoch [7400/10000], Loss: 0.0381
Epoch [7500/10000], Loss: 0.0380
Epoch [7600/10000], Loss: 0.0379
Epoch [7700/10000], Loss: 0.0378
Epoch [7800/10000], Loss: 0.0378
Epoch [7900/10000], Loss: 0.0377
Epoch [8000/10000], Loss: 0.0377
Epoch [8100/10000], Loss: 0.0377
Epoch [8200/10000], Loss: 0.0377
Epoch [8300/10000], Loss: 0.0376
Epoch [8400/10000], Loss: 0.0376
Epoch [8500/10000], Loss: 0.0375
Epoch [8600/10000], Loss: 0.0375
Epoch [8700/10000], Loss: 0.0374
Epoch [8800/10000], Loss: 0.0373
Epoch [8900/10000], Loss: 0.0373
Epoch [9000/10000], Loss: 0.0373
Epoch [9100/10000], Loss: 0.0372
Epoch [9200/10000], Loss: 0.0372
Epoch [9300/10000], Loss: 0.0372
Epoch [9400/10000], Loss: 0.0372
Epoch [9500/10000], Loss: 0.0371
Epoch [9600/10000], Loss: 0.0368
Epoch [9700/10000], Loss: 0.0366
Epoch [9800/10000], Loss: 0.0364
Epoch [9900/10000], Loss: 0.0363
Epoch [10000/10000], Loss: 0.0363
Mean Squared Error on Test Set: 0.1760

In [ ]:
from sklearn.metrics import r2_score


# Convert data to PyTorch tensors
X_train_tensor = torch.FloatTensor(X_train)
y_train_tensor = torch.FloatTensor(y_train).view(-1, 1)  # Reshape to a column vector
X_test_tensor = torch.FloatTensor(X_test)
y_test_tensor = torch.FloatTensor(y_test).view(-1, 1)  # Reshape to a column vector

# Define the neural network model
class HousePricePredictor(nn.Module):
    def __init__(self, input_size, hidden_size1,hidden_size2, output_size):
        super(HousePricePredictor, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size1)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size1, hidden_size2)
        self.layer3 = nn.Linear(hidden_size2, output_size)

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

# Instantiate the model
input_size = X_train.shape[1]
hidden_size1 = 16  # Adjust as needed
hidden_size2=8
output_size = 1
model = HousePricePredictor(input_size, hidden_size1,hidden_size2, output_size)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
num_epochs = 5000

for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print progress
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Evaluate the model on the test set
with torch.no_grad():
    model.eval()
    predictions = model(X_test_tensor)
    mse = mean_squared_error(y_test, predictions.numpy())
    print(f'Mean Squared Error on Test Set: {mse:.4f}')
# Evaluate the model on the test set
with torch.no_grad():
    model.eval()
    predictions = model(X_test_tensor)

    # Calculate R-squared
    r2 = r2_score(y_test, predictions.numpy())
    print(f'R-squared on Test Set: {r2:.4f}')

# Function to predict house price using the trained model
def predict_house_price(model, input_features, scaler):
    # Standardize input features using the same scaler used for training
    input_features_standardized = scaler.transform(input_features)

    # Convert to PyTorch tensor
    input_tensor = torch.FloatTensor(input_features_standardized)

    # Make the prediction
    with torch.no_grad():
        model.eval()
        predicted_price = model(input_tensor)

    return predicted_price.item()

# Example usage:
# Replace the values in the input_features array with your own input values
input_features = np.array([[3000, 1, 0,
                            1, 0, 0,
                            0, 0, 600]])


# Use the predict_house_price function
predicted_price = predict_house_price(model, input_features, scaler)

print(f'Predicted House Price: {predicted_price:.2f}')

Epoch [100/5000], Loss: 191.1612
Epoch [200/5000], Loss: 50.8008
Epoch [300/5000], Loss: 8.4452
Epoch [400/5000], Loss: 4.2448
Epoch [500/5000], Loss: 2.5802
Epoch [600/5000], Loss: 1.6824
Epoch [700/5000], Loss: 1.1651
Epoch [800/5000], Loss: 0.8629
Epoch [900/5000], Loss: 0.6750
Epoch [1000/5000], Loss: 0.5487
Epoch [1100/5000], Loss: 0.4550
Epoch [1200/5000], Loss: 0.3828
Epoch [1300/5000], Loss: 0.3303
Epoch [1400/5000], Loss: 0.2873
Epoch [1500/5000], Loss: 0.2514
Epoch [1600/5000], Loss: 0.2228
Epoch [1700/5000], Loss: 0.1989
Epoch [1800/5000], Loss: 0.1791
Epoch [1900/5000], Loss: 0.1629
Epoch [2000/5000], Loss: 0.1486
Epoch [2100/5000], Loss: 0.1363
Epoch [2200/5000], Loss: 0.1253
Epoch [2300/5000], Loss: 0.1160
Epoch [2400/5000], Loss: 0.1075
Epoch [2500/5000], Loss: 0.0997
Epoch [2600/5000], Loss: 0.0926
Epoch [2700/5000], Loss: 0.0868
Epoch [2800/5000], Loss: 0.0812
Epoch [2900/5000], Loss: 0.0767
Epoch [3000/5000], Loss: 0.0729
Epoch [3100/5000], Loss: 0.0694
Epoch [3200/5000], Loss: 0.0666
Epoch [3300/5000], Loss: 0.0641
Epoch [3400/5000], Loss: 0.0619
Epoch [3500/5000], Loss: 0.0599
Epoch [3600/5000], Loss: 0.0580
Epoch [3700/5000], Loss: 0.0564
Epoch [3800/5000], Loss: 0.0546
Epoch [3900/5000], Loss: 0.0524
Epoch [4000/5000], Loss: 0.0508
Epoch [4100/5000], Loss: 0.0494
Epoch [4200/5000], Loss: 0.0481
Epoch [4300/5000], Loss: 0.0468
Epoch [4400/5000], Loss: 0.0456
Epoch [4500/5000], Loss: 0.0446
Epoch [4600/5000], Loss: 0.0438
Epoch [4700/5000], Loss: 0.0432
Epoch [4800/5000], Loss: 0.0427
Epoch [4900/5000], Loss: 0.0422
Epoch [5000/5000], Loss: 0.0417
Mean Squared Error on Test Set: 0.0923
R-squared on Test Set: 0.3051
Predicted House Price: 14.61

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
X

array([[ 1.04672629,  1.42181174,  0.40562287, ...,  1.4726183 ,
         1.80494113, -0.52454873],
       [ 1.75700953,  5.40580863,  0.40562287, ...,  1.4726183 ,
        -0.55403469, -0.96099744],
       [ 2.21823241,  1.42181174,  0.40562287, ..., -0.67906259,
         1.80494113,  0.28365009],
       ...,
       [-0.70592066, -0.57018671,  0.40562287, ..., -0.67906259,
        -0.55403469,  0.20998335],
       [-1.03338891, -0.57018671, -2.46534421, ..., -0.67906259,
        -0.55403469, -0.24482866],
       [-0.5998394 , -0.57018671,  0.40562287, ..., -0.67906259,
        -0.55403469, -0.25924172]])